# User config
author: "Sarah Allen"
tagline: "Who dat (villager?)"
description: "Animal crossing classifier model using fastai and resnet18 model"
keywords: "Animal Crossing, AI, New Horizons"
email: "allensarahanne@gmail.com"
linkedin: "https://www.linkedin.com/sarahallen"
github: "https://github.com/sarahallen"

# Site config
domain: villager-snoop.github.io       
url: https://villager-snoop.github.io
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
